# %%
import folium
import geopandas as gpd
import polars as pl
import streamlit as st
from dbnomics import fetch_series
from streamlit_folium import folium_static

# %%
# télécharger les données from dbnomics
list_iso3 = [
    "AFG",
    "ALB",
    "DZA",
    "AND",
    "AGO",
    "ATG",
    "ARG",
    "ARM",
    "AUS",
    "AUT",
    "AZE",
    "BHS",
    "BHR",
    "BGD",
    "BRB",
    "BLR",
    "BEL",
    "BLZ",
    "BEN",
    "BTN",
    "BOL",
    "BIH",
    "BWA",
    "BRA",
    "BRN",
    "BGR",
    "BFA",
    "BDI",
    "CPV",
    "KHM",
    "CMR",
    "CAN",
    "CAF",
    "TCD",
    "CHL",
    "CHN",
    "COL",
    "COM",
    "COG",
    "COD",
    "CRI",
    "CIV",
    "HRV",
    "CUB",
    "CYP",
    "CZE",
    "DNK",
    "DJI",
    "DMA",
    "DOM",
    "ECU",
    "EGY",
    "SLV",
    "GNQ",
    "ERI",
    "EST",
    "SWZ",
    "ETH",
    "FJI",
    "FIN",
    "FRA",
    "GAB",
    "GMB",
    "GEO",
    "DEU",
    "GHA",
    "GRC",
    "GRD",
    "GTM",
    "GIN",
    "GNB",
    "GUY",
    "HTI",
    "HND",
    "HUN",
    "ISL",
    "IND",
    "IDN",
    "IRN",
    "IRQ",
    "IRL",
    "ISR",
    "ITA",
    "JAM",
    "JPN",
    "JOR",
    "KAZ",
    "KEN",
    "KIR",
    "KWT",
    "KGZ",
    "LAO",
    "LVA",
    "LBN",
    "LSO",
    "LBR",
    "LBY",
    "LIE",
    "LTU",
    "LUX",
    "MDG",
    "MWI",
    "MYS",
    "MDV",
    "MLI",
    "MLT",
    "MHL",
    "MRT",
    "MUS",
    "MEX",
    "FSM",
    "MDA",
    "MCO",
    "MNG",
    "MNE",
    "MAR",
    "MOZ",
    "MMR",
    "NAM",
    "NRU",
    "NPL",
    "NLD",
    "NZL",
    "NIC",
    "NER",
    "NGA",
    "PRK",
    "MKD",
    "NOR",
    "OMN",
    "PAK",
    "PLW",
    "PAN",
    "PNG",
    "PRY",
    "PER",
    "PHL",
    "POL",
    "PRT",
    "QAT",
    "ROU",
    "RUS",
    "RWA",
    "KNA",
    "LCA",
    "VCT",
    "WSM",
    "SMR",
    "STP",
    "SAU",
    "SEN",
    "SRB",
    "SYC",
    "SLE",
    "SGP",
    "SVK",
    "SVN",
    "SLB",
    "SOM",
    "ZAF",
    "KOR",
    "SSD",
    "ESP",
    "LKA",
    "SDN",
    "SUR",
    "SWE",
    "CHE",
    "SYR",
    "TJK",
    "TZA",
    "THA",
    "TLS",
    "TGO",
    "TON",
    "TTO",
    "TUN",
    "TUR",
    "TKM",
    "TUV",
    "UGA",
    "UKR",
    "ARE",
    "GBR",
    "USA",
    "URY",
    "UZB",
    "VUT",
    "VAT",
    "VEN",
    "VNM",
    "YEM",
    "ZMB",
    "ZWE",
]

# Annual Trade in % of GDP
df = fetch_series(
    "WB",
    "WDI",
    dimensions={
        "frequency": ["A"],
        "indicator": ["NE.TRD.GNFS.ZS"],
        "country": list_iso3,
    },
    max_nb_series=200,
)
# %%
# Charger les données géographiques des pays
world = gpd.read_file("/home/juliette/projets/trade/src/trade/natural_earth")
# %%
df = pl.from_pandas(df)
# %%
df_mean = df.group_by(pl.col("country").alias("country")).agg(
    [pl.col("value").mean().alias("mean trade"), pl.col("country.label")]
)
# %%
# Exemple de données d'échanges (à remplacer par vos données)
# Fusionner les données géographiques avec les données d'échanges
world = world.merge(df, how="left", left_on="iso_a3", right_on="country_code")

# Créer une carte Folium
m = folium.Map(location=[30, 0], zoom_start=2)

# Ajouter les pays à la carte avec des couleurs en fonction du volume d'échanges
folium.Choropleth(
    geo_data=world,
    name="choropleth",
    data=world,
    columns=["iso_a3", "trade_volume"],
    key_on="feature.properties.iso_a3",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Volume des échanges",
).add_to(m)

# Ajouter des tooltips pour afficher le nom du pays et le volume d'échanges
folium.features.GeoJson(
    world,
    name="Labels",
    style_function=lambda x: {
        "color": "transparent",
        "fillColor": "transparent",
        "weight": 0,
    },
    tooltip=folium.features.GeoJsonTooltip(
        fields=["name", "trade_volume"],
        aliases=["Pays:", "Volume des échanges:"],
        labels=True,
        sticky=True,
    ),
).add_to(m)

# Afficher la carte dans Streamlit
st.title("Carte des échanges commerciaux")
folium_static(m)
